import type { Metadata } from "next";
import ThemeRegistry from "@/components/themeRegistry/ThemeRegistry";
import AuthProvider from "../providers/AuthProvider";
import "./globals.css";
import ReduxProvider from "@/redux/provider";

export const metadata: Metadata = {
  title: "PEOPayGo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <ThemeRegistry>
        <body>
          <AuthProvider>
            <ReduxProvider>
              {children}
            </ReduxProvider>
          </AuthProvider>
        </body>
      </ThemeRegistry>
    </html>
  );
}
